name: detect_testflight
description: Detect if the Flutter app is running from TestFlight at runtime
version: 2.0.0
homepage: https://declan.sh

environment:
  sdk: '>=2.12.0 <4.0.0'
  flutter: ">=3.19.4"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: sh.declan.detect_testflight
        pluginClass: DetectTestflightPlugin
      ios:
        pluginClass: DetectTestflightPlugin
      web:
        pluginClass: DetectTestflightPlugin
        fileName: detect_testflight.dart
